progA:progA.o
	gcc -std=c11 -Wall -pedantic -o progA progA.c
progA.o:progA.c
	gcc -std=c11 -Wall -pedantic -c progA.c

progB:progB.o
	gcc -std=c11 -Wall -pedantic -o progB progB.c
progB.o:progB.c
	gcc -std=c11 -Wall -pedantic -c progB.c

progC:progC.o
	gcc -std=c11 -Wall -pedantic -o progC progC.c
progC.o:progC.c
	gcc -std=c11 -Wall -pedantic -c progC.c
